"""
Evox CLI - Command line interface for the Evox framework

This module provides the command-line interface for managing Evox projects,
services, and platform operations including the new health monitoring system.
"""

import os
import sys
import webbrowser
import tempfile
from pathlib import Path
import typer
from typing import Optional
import json
from datetime import datetime


app = typer.Typer(
    name="evox",
    help="Evox - Modern Python Microservices Framework CLI",
    no_args_is_help=True
)


@app.command()
def new(
    project_type: str = typer.Argument(..., help="Type of project to create (pj for project, sv for service)"),
    name: str = typer.Argument(..., help="Name of the project or service")
):
    """Create a new Evox project or service"""
    if project_type == "pj":
        create_project(name)
    elif project_type == "sv":
        create_service(name)
    else:
        typer.echo(f"Invalid project type: {project_type}. Use 'pj' for project or 'sv' for service.")
        raise typer.Exit(code=1)


def create_project(name: str):
    """Create a new Evox project"""
    project_path = Path(name)
    
    if project_path.exists():
        typer.echo(f"Project directory '{name}' already exists!")
        raise typer.Exit(code=1)
    
    # Create project structure
    project_path.mkdir(parents=True)
    
    # Create basic project files
    (project_path / "services").mkdir()
    
    # Create config.toml from template
    template_path = Path(__file__).parent / "templates" / "config.toml"
    if template_path.exists():
        config_content = template_path.read_text().replace("{{ project_name }}", name)
        (project_path / "config.toml").write_text(config_content)
    else:
        (project_path / "config.toml").write_text("# Evox Project Configuration\n")
        
    (project_path / ".env.example").write_text("# Environment variables\n")
    (project_path / "README.md").write_text(f"# {name}\n\nEvox project created with `evox new pj {name}`\n")
    
    # Create pyproject.toml with Rye configuration
    pyproject_content = f'''[project]
name = "{name}"
version = "0.1.0"
description = "Evox microservices project"
authors = [
    {{ name = "Developer", email = "dev@example.com" }}
]
dependencies = [
    "evox>=0.0.1-alpha",
]
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["services"]

[project.scripts]
dev = "evox.cli.main:run_dev"
'''
    
    (project_path / "pyproject.toml").write_text(pyproject_content)
    
    typer.echo(f"✅ Created Evox project '{name}' at {project_path.absolute()}")


def create_service(name: str):
    """Create a new Evox service"""
    service_path = Path("services") / name
    
    if not Path("services").exists():
        typer.echo("Error: 'services' directory not found. Run this command from an Evox project root.")
        raise typer.Exit(code=1)
    
    if service_path.exists():
        typer.echo(f"Service directory '{name}' already exists!")
        raise typer.Exit(code=1)
    
    # Create service structure
    service_path.mkdir(parents=True)
    
    # Create service template with Evox syntax
    main_py_content = f'''"""
{name} Service - Generated by Evox CLI
"""
from evox.core import service, get, post, endpoint, proxy, data_io, data_intent

# Create service
svc = service("{name}") \\
    .port(8000) \\
    .health("/health") \\
    .build()

# Example GET endpoint with data intent
@get("/users/{{user_id}}")
async def get_user(user_id: int):
    # Read user data with intent-aware behavior
    user = await data_io.read(f"user:{{user_id}}")
    if user:
        return user
    
    # Mock user data
    user = {{
        "id": user_id,
        "name": f"User {{user_id}}",
        "email": f"user{{user_id}}@example.com"
    }}
    
    # Write with intent (cacheable for 1 hour)
    await data_io.write(f"user:{{user_id}}", user, ttl=3600)
    return user

# Example POST endpoint with data intent
@post("/users")
@data_intent.cacheable(ttl="1h", consistency="eventual")
async def create_user(user_data: dict):
    user_id = user_data.get("id", 1)
    user = {{
        "id": user_id,
        "name": user_data.get("name", "Unknown"),
        "email": user_data.get("email", "unknown@example.com")
    }}
    
    # Write user data with intent
    await data_io.write(f"user:{{user_id}}", user, ttl=3600)
    return {{"status": "created", "user": user}}

# Internal endpoint (not exposed as route)
@endpoint()
async def process_user_data(user_id: int, data: dict):
    # Process user data internally
    processed_data = {{"user_id": user_id, "processed": True, "data": data}}
    return processed_data

# Example background task
@svc.background_task(interval=60)
async def cleanup_expired_data():
    # Cleanup expired data periodically
    print("Cleaning up expired data...")

# Example startup handler
@svc.on_startup
async def startup():
    print("{name} service started")

# Example shutdown handler
@svc.on_shutdown
async def shutdown():
    print("{name} service stopped")

if __name__ == "__main__":
    svc.run(dev=True)
'''
    
    (service_path / "main.py").write_text(main_py_content)
    
    # Create config.toml with data intent configuration
    config_content = f'''# {name} Service Configuration
name = "{name}"
version = "0.1.0"
port = 8000

# Connection method: router, rest, hybrid, disabled
connection_method = "hybrid"

# Prerequisites - checked by 'evox sync sv'
prerequisites = ["data_intent_svc"]

[health]
endpoint = "/health"

[data_intents]
# Default data intent behaviors
default_ttl = 300
enable_fallback = true
max_stale_on_error = 60

[storage]
backend = "memory"  # memory, sqlite
'''
    
    (service_path / "config.toml").write_text(config_content)
    
    typer.echo(f"✅ Created Evox service '{name}' at {service_path.absolute()}")


@app.command()
def run(dev: bool = typer.Option(False, "--dev", help="Run in development mode with auto-reload")):
    """Run the Evox platform"""
    typer.echo("🏃 Running Evox platform...")
    # In a full implementation, this would start the orchestrator
    # For now, we'll just show a message
    typer.echo("Platform would start here...")


@app.command()
def sync(
    sync_type: str = typer.Argument(..., help="Type of sync to perform (db for database, sv for services)")
):
    """Sync database or services"""
    if sync_type == "db":
        typer.echo("🔄 Syncing database...")
        # Database sync logic would go here
        typer.echo("Database sync completed")
    elif sync_type == "sv":
        typer.echo("🔄 Syncing services...")
        # Service sync logic would go here
        typer.echo("Service sync completed")
    else:
        typer.echo(f"Invalid sync type: {sync_type}. Use 'db' for database or 'sv' for services.")
        raise typer.Exit(code=1)


@app.command()
def status():
    """Show platform status"""
    typer.echo("📊 Evox Platform Status")
    typer.echo("  Services: Platform initializing")
    typer.echo("  Health: Unknown")
    typer.echo("  Cache: Not connected")


@app.command()
def cache(
    operation: str = typer.Argument(..., help="Cache operation (invalidate)"),
    key: str = typer.Argument(None, help="Cache key to invalidate")
):
    """Manage cache"""
    if operation == "invalidate":
        if key:
            typer.echo(f"🗑️  Invalidating cache key: {key}")
        else:
            typer.echo("🗑️  Invalidating all cache")
    else:
        typer.echo(f"Invalid cache operation: {operation}")


@app.command()
def test():
    """Run tests"""
    typer.echo("🧪 Running tests...")
    # In a real implementation, this would run the test suite
    typer.echo("Tests completed")


@app.command()
def dashboard():
    """Open admin dashboard"""
    typer.echo("🖥️  Opening admin dashboard...")
    # In a real implementation, this would open a web browser
    typer.echo("Dashboard opened")


@app.command()
def health():
    """Generate system health report and open in browser"""
    typer.echo("🏥 Generating system health report...")
    
    # Generate health report data
    report_data = generate_health_report()
    
    # Create HTML report
    html_content = generate_html_report(report_data)
    
    # Save to temporary file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.html', delete=False) as f:
        f.write(html_content)
        temp_file = f.name
    
    # Try to open in browser
    try:
        webbrowser.open(f'file://{temp_file}')
        typer.echo(f"✅ Health report opened in browser: {temp_file}")
    except Exception as e:
        typer.echo(f"⚠️  Could not open browser: {e}")
        typer.echo("📋 Health report summary:")
        print_health_summary(report_data)


def generate_health_report():
    """Generate comprehensive health report data
    
    Returns:
        Dict containing health report data
    """
    # In a real implementation, this would collect actual system metrics
    # For now, we'll generate mock data to demonstrate the feature
    
    return {
        "generated_at": datetime.now().isoformat(),
        "overall_status": "green",  # green, yellow, red
        "services": [
            {
                "name": "data_intent_svc",
                "status": "up",
                "port": 8000,
                "connection_method": "router",
                "health_endpoint": "/health",
                "health_result": {"status": "healthy"},
                "last_checked": datetime.now().isoformat()
            },
            {
                "name": "user_svc",
                "status": "up",
                "port": 8001,
                "connection_method": "rest",
                "health_endpoint": "/health",
                "health_result": {"status": "healthy", "uptime": "2h 15m"},
                "last_checked": datetime.now().isoformat()
            }
        ],
        "registry_contents": [
            {"key": "service:data_intent_svc", "value": "running on port 8000"},
            {"key": "service:user_svc", "value": "running on port 8001"},
            {"key": "config:storage_backend", "value": "memory"}
        ],
        "cache_stats": {
            "hits": 1247,
            "misses": 89,
            "hit_rate": 0.933,
            "stale_served": 12,
            "entries": 156
        },
        "data_intents": {
            "active_intents": [
                {"type": "cacheable", "count": 24, "ttl_range": "1m-24h"},
                {"type": "strong_consistency", "count": 3, "services": ["user_svc"]},
                {"type": "eventual_ok", "count": 17, "services": ["data_intent_svc", "user_svc"]}
            ],
            "backends_in_use": ["memory", "sqlite"]
        },
        "queue_stats": {
            "high_priority": {"length": 0, "processed": 42, "rejections": 0},
            "medium_priority": {"length": 2, "processed": 128, "rejections": 1},
            "low_priority": {"length": 5, "processed": 67, "rejections": 3},
            "active_workers": {"high": 2, "medium": 3, "low": 1}
        },
        "recent_errors": [
            {
                "timestamp": (datetime.now().replace(minute=15)).isoformat(),
                "service": "user_svc",
                "error": "Connection timeout",
                "reason": "Database connection pool exhausted",
                "resolved": True
            }
        ],
        "dependency_validation": {
            "passed": True,
            "checks": [
                {"name": "Python version", "status": "pass", "details": "3.11.5"},
                {"name": "Required packages", "status": "pass", "details": "All dependencies satisfied"},
                {"name": "Network connectivity", "status": "pass", "details": "All services reachable"}
            ]
        }
    }


def generate_html_report(data):
    """Generate HTML report from health data
    
    Args:
        data: Health report data dictionary
        
    Returns:
        String containing HTML report
    """
    # Status color mapping
    status_colors = {
        "green": "#4CAF50",
        "yellow": "#FFC107",
        "red": "#F44336"
    }
    
    # Generate HTML content
    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Evox System Health Report</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            overflow: hidden;
        }}
        .header {{
            background: #2c3e50;
            color: white;
            padding: 20px;
            text-align: center;
        }}
        .status-badge {{
            display: inline-block;
            padding: 8px 16px;
            border-radius: 20px;
            font-weight: bold;
            background-color: {status_colors.get(data['overall_status'], '#9E9E9E')};
        }}
        .section {{
            padding: 20px;
            border-bottom: 1px solid #eee;
        }}
        .section:last-child {{
            border-bottom: none;
        }}
        .section-title {{
            color: #2c3e50;
            margin-top: 0;
            padding-bottom: 10px;
            border-bottom: 2px solid #eee;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background-color: #f8f9fa;
            font-weight: 600;
        }}
        tr:hover {{
            background-color: #f5f5f5;
        }}
        .collapsible {{
            background-color: #f1f1f1;
            color: #444;
            cursor: pointer;
            padding: 10px;
            width: 100%;
            border: none;
            text-align: left;
            outline: none;
            font-size: 15px;
            margin: 5px 0;
        }}
        .active, .collapsible:hover {{
            background-color: #ccc;
        }}
        .content {{
            padding: 0 18px;
            display: none;
            overflow: hidden;
            background-color: #f9f9f9;
        }}
        .metric-card {{
            background: #f8f9fa;
            border-radius: 6px;
            padding: 15px;
            margin: 10px 0;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }}
        .metric-value {{
            font-size: 24px;
            font-weight: bold;
            color: #2c3e50;
        }}
        .metric-label {{
            font-size: 14px;
            color: #666;
        }}
        .error {{
            background-color: #ffebee;
            border-left: 4px solid #f44336;
            padding: 15px;
            margin: 10px 0;
        }}
        .warning {{
            background-color: #fff3e0;
            border-left: 4px solid #ff9800;
            padding: 15px;
            margin: 10px 0;
        }}
        .success {{
            background-color: #e8f5e9;
            border-left: 4px solid #4caf50;
            padding: 15px;
            margin: 10px 0;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Evox System Health Report</h1>
            <p>Generated at: {data['generated_at']}</p>
            <span class="status-badge">Overall Status: {data['overall_status'].upper()}</span>
        </div>
        
        <!-- Services Section -->
        <div class="section">
            <h2 class="section-title">Service Status</h2>
            <table>
                <thead>
                    <tr>
                        <th>Service</th>
                        <th>Status</th>
                        <th>Port</th>
                        <th>Connection</th>
                        <th>Health Endpoint</th>
                        <th>Last Checked</th>
                    </tr>
                </thead>
                <tbody>
    """
    
    # Add service rows
    for service in data['services']:
        status_color = "green" if service['status'] == 'up' else "red"
        html += f"""
                    <tr>
                        <td>{service['name']}</td>
                        <td><span style="color: {status_colors.get(status_color, '#9E9E9E')}; font-weight: bold;">{service['status'].upper()}</span></td>
                        <td>{service['port']}</td>
                        <td>{service['connection_method']}</td>
                        <td>{service['health_endpoint']}</td>
                        <td>{service['last_checked'][:19]}</td>
                    </tr>
        """
    
    html += """
                </tbody>
            </table>
        </div>
        
        <!-- Registry Contents -->
        <div class="section">
            <h2 class="section-title">Registry Contents</h2>
            <table>
                <thead>
                    <tr>
                        <th>Key</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
    """
    
    # Add registry rows
    for item in data['registry_contents']:
        html += f"""
                    <tr>
                        <td>{item['key']}</td>
                        <td>{item['value']}</td>
                    </tr>
        """
    
    html += """
                </tbody>
            </table>
        </div>
        
        <!-- Cache Stats -->
        <div class="section">
            <h2 class="section-title">Cache Statistics</h2>
            <div style="display: flex; flex-wrap: wrap;">
                <div class="metric-card">
                    <div class="metric-value">{data['cache_stats']['hits']}</div>
                    <div class="metric-label">Cache Hits</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{data['cache_stats']['misses']}</div>
                    <div class="metric-label">Cache Misses</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{data['cache_stats']['hit_rate']:.2%}</div>
                    <div class="metric-label">Hit Rate</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{data['cache_stats']['stale_served']}</div>
                    <div class="metric-label">Stale Data Served</div>
                </div>
            </div>
        </div>
        
        <!-- Data Intents -->
        <div class="section">
            <h2 class="section-title">Data Intent Summary</h2>
            <button class="collapsible">Active Data Intents</button>
            <div class="content">
                <table>
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Count</th>
                            <th>Details</th>
                        </tr>
                    </thead>
                    <tbody>
    """
    
    # Add data intent rows
    for intent in data['data_intents']['active_intents']:
        services = ", ".join(intent.get('services', [])) if intent.get('services') else "Various"
        html += f"""
                        <tr>
                            <td>{intent['type']}</td>
                            <td>{intent['count']}</td>
                            <td>{intent.get('ttl_range', services)}</td>
                        </tr>
        """
    
    html += f"""
                    </tbody>
                </table>
            </div>
            <div class="metric-card">
                <div class="metric-value">{', '.join(data['data_intents']['backends_in_use'])}</div>
                <div class="metric-label">Backends in Use</div>
            </div>
        </div>
        
        <!-- Queue Stats -->
        <div class="section">
            <h2 class="section-title">Priority Queue Statistics</h2>
            <div style="display: flex; flex-wrap: wrap;">
                <div class="metric-card">
                    <div class="metric-value">{data['queue_stats']['high_priority']['length']}</div>
                    <div class="metric-label">High Priority Queue Length</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{data['queue_stats']['medium_priority']['length']}</div>
                    <div class="metric-label">Medium Priority Queue Length</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{data['queue_stats']['low_priority']['length']}</div>
                    <div class="metric-label">Low Priority Queue Length</div>
                </div>
            </div>
            <div style="display: flex; flex-wrap: wrap; margin-top: 15px;">
                <div class="metric-card">
                    <div class="metric-value">{data['queue_stats']['high_priority']['rejections']}</div>
                    <div class="metric-label">High Priority Rejections</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{data['queue_stats']['medium_priority']['rejections']}</div>
                    <div class="metric-label">Medium Priority Rejections</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{data['queue_stats']['low_priority']['rejections']}</div>
                    <div class="metric-label">Low Priority Rejections</div>
                </div>
            </div>
        </div>
        
        <!-- Recent Errors -->
        <div class="section">
            <h2 class="section-title">Recent Errors & Warnings</h2>
    """
    
    # Add error entries
    if data['recent_errors']:
        for error in data['recent_errors']:
            resolved_class = "success" if error.get('resolved', False) else "error"
            resolved_text = "RESOLVED" if error.get('resolved', False) else "ACTIVE"
            html += f"""
            <div class="{resolved_class}">
                <strong>{error['timestamp'][:19]}</strong> - {error['service']}<br>
                <strong>Error:</strong> {error['error']}<br>
                <strong>Reason:</strong> {error['reason']}<br>
                <strong>Status:</strong> {resolved_text}
            </div>
            """
    else:
        html += """
            <div class="success">
                No recent errors detected
            </div>
        """
    
    html += """
        </div>
        
        <!-- Dependency Validation -->
        <div class="section">
            <h2 class="section-title">Dependency Validation</h2>
    """
    
    # Add dependency validation results
    if data['dependency_validation']['passed']:
        html += """
            <div class="success">
                <strong>All dependency checks passed</strong>
        """
    else:
        html += """
            <div class="error">
                <strong>Dependency validation failed</strong>
        """
    
    html += """
                <ul>
    """
    
    # Add individual checks
    for check in data['dependency_validation']['checks']:
        status_icon = "✓" if check['status'] == 'pass' else "✗"
        html += f"""
                    <li>{status_icon} {check['name']}: {check['details']}</li>
        """
    
    html += """
                </ul>
            </div>
        </div>
        
        <div class="section" style="text-align: center; background: #f8f9fa;">
            <p><em>Report generated by Evox v0.0.1-alpha - Data-Intent-Aware Framework</em></p>
        </div>
    </div>
    
    <script>
        // Collapsible sections
        var coll = document.getElementsByClassName("collapsible");
        var i;
        
        for (i = 0; i < coll.length; i++) {{
            coll[i].addEventListener("click", function() {{
                this.classList.toggle("active");
                var content = this.nextElementSibling;
                if (content.style.display === "block") {{
                    content.style.display = "none";
                }} else {{
                    content.style.display = "block";
                }}
            }});
        }}
    </script>
</body>
</html>
    """
    
    return html


def print_health_summary(data):
    """Print a text summary of the health report
    
    Args:
        data: Health report data dictionary
    """
    typer.echo("\n🏥 Evox System Health Summary")
    typer.echo("=" * 40)
    typer.echo(f"Generated at: {data['generated_at']}")
    typer.echo(f"Overall Status: {data['overall_status'].upper()}")
    
    typer.echo("\n🔌 Service Status:")
    for service in data['services']:
        status_indicator = "✅" if service['status'] == 'up' else "❌"
        typer.echo(f"  {status_indicator} {service['name']} - Port {service['port']} - {service['status'].upper()}")
    
    typer.echo(f"\nキャッシング Cache Stats:")
    typer.echo(f"  Hits: {data['cache_stats']['hits']}")
    typer.echo(f"  Misses: {data['cache_stats']['misses']}")
    typer.echo(f"  Hit Rate: {data['cache_stats']['hit_rate']:.2%}")
    typer.echo(f"  Stale Data Served: {data['cache_stats']['stale_served']}")
    
    typer.echo(f"\n⚡ Queue Stats:")
    typer.echo(f"  High Priority: {data['queue_stats']['high_priority']['length']} items")
    typer.echo(f"  Medium Priority: {data['queue_stats']['medium_priority']['length']} items")
    typer.echo(f"  Low Priority: {data['queue_stats']['low_priority']['length']} items")
    
    if data['recent_errors']:
        typer.echo(f"\n⚠️  Recent Errors:")
        for error in data['recent_errors']:
            status = "RESOLVED" if error.get('resolved', False) else "ACTIVE"
            typer.echo(f"  [{status}] {error['service']}: {error['error']}")
    else:
        typer.echo(f"\n✅ No Recent Errors")


@app.callback()
def callback():
    """Evox - Modern Python Microservices Framework"""


if __name__ == "__main__":
    app()